### PR TITLE
Add external data checker for automatic update PRs.

### PR DESCRIPTION
**Pull request by RayJW**
This PR adds the x-checker-data for the Upscayl git repository. This will function the same way as [here](https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/122), which I also implemented, and will make maintenance easier as the only update step will be merging the PR as soon as the Flatpak should be brought on par with upstream.

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Sorry, I don't understand. Would this mean we wouldn't need to update the checksum manually every time we have a new release?

**Comment by RayJW** [comment]
Exactly. Every time there is a new GitHub release, the bot will open a PR that updates the version and checksum to the newest one. I linked one of these PRs as an example [here](https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/122). At the end you can still manually decide if you want to merge it if you don't enable automerging in the config file (which is off by default) but it just makes it easier since you don't have to fix the checksum, release date etc. manually every time.

**Comment by NayamAmarshe** [comment]
> Exactly. Every time there is a new GitHub release, the bot will open a PR that updates the version and checksum to the newest one. I linked one of these PRs as an example [here](https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/122). At the end you can still manually decide if you want to merge it if you don't enable automerging in the config file (which is off by default) but it just makes it easier since you don't have to fix the checksum, release date etc. manually every time.

That's awesome! I didn't know this was a thing although I did suspect there should be😅

Thank you, I'll merge.

Why do we not need to add the x-data-checker for the xml file though?

**Comment by RayJW** [comment]
> Why do we not need to add the x-data-checker for the xml file though?

Because, I didn't realise it wasn't part of this repository😂

I will add one for the xml as well as I get to it :)

**Comment by NayamAmarshe** [comment]
> > Why do we not need to add the x-data-checker for the xml file though?
> 
> Because, I didn't realise it wasn't part of this repository😂
> 
> I will add one for the xml as well as I get to it :)

and after adding the external check, do we not need to delete the sha256 key?

**Comment by RayJW** [comment]
> and after adding the external check, do we not need to delete the sha256 key?

No need, as you can see in the example PR, the bot also updates the hash. If I may ask, is there any reason that you have the XML in the project repo instead of here, and I saw there is also a mirror of the YAML file in the repo? Because I think there is no way for me to check for just the latest Git version of the XML, the only way I see would be updating it once a new Git release is tagged, but that is probably not always the case. [Those](https://github.com/flathub/flatpak-external-data-checker) are the possible checker methods.

**Comment by NayamAmarshe** [comment]
> > and after adding the external check, do we not need to delete the sha256 key?
> 
> No need, as you can see in the example PR, the bot also updates the hash. If I may ask, is there any reason that you have the XML in the project repo instead of here, and I saw there is also a mirror of the YAML file in the repo? Because I think there is no way for me to check for just the latest Git version of the XML, the only way I see would be updating it once a new Git release is tagged, but that is probably not always the case. [Those](https://github.com/flathub/flatpak-external-data-checker) are the possible checker methods.

The flathub team asked us to not keep those files in the repository. So we had to put the xml there.

As for the yaml, we can delete the redundant file.

**Comment by RayJW** [comment]
Do you mean [this comment](https://github.com/flathub/flathub/pull/3779#discussion_r1188548485)? I think they only meant that it shouldn't be in two places. If you don't need the XML for the upstream app, I would move it here, because otherwise it's difficult to keep them in line. Because there are a lot of apps that have the XML directly in the Flathub repo, like [here](https://github.com/flathub/com.synology.SynologyDrive) or [here](https://github.com/flathub/ch.protonmail.protonmail-bridge).

This would also clean up the upstream repo. Because that way you could delete the whole Flatpak folder.

**Comment by RayJW** [comment]
@NayamAmarshe I interpreted your reaction as approval. So, I went ahead and added the XML to the repo and removed the remote reference in the YAML.

**Pull request merged**
